FROM java:8
MAINTAINER Ethan Ma <yixing.ma@gmail.com>
LABEL com.weshaka.label=ole_svc_1.0.0
ADD ole-svc-1.0.0.jar /app/ole-svc-1.0.0.jar
EXPOSE 8080 9089
CMD ["java", "-jar", "/app/ole-svc-1.0.0.jar"]